version: 2

jobs:
  build:
    tags:
      only: /.*/
    docker:
      - image: node:8.8.0
    environment:
      - NPM_CONFIG_LOGLEVEL: warn
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - deploy:
          name: Create Tag
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              node ./src/createTag/index.js;
            fi
      - deploy:
          name: Create Release
          command: |
            if [ "${CIRCLE_TAG}" != "" ]; then
              node ./src/createRelease/index.js;
            fi
