version: 2

jobs:
  build-job:
    working_directory: ~/repo
    environment:
      - NPM_CONFIG_LOGLEVEL: warn
    docker:
      - image: node:8.8.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
  create-tag:
    working_directory: ~/repo
    docker:
      - image: node:8.8.0
    steps:
      - run:
          name: Create Tag
          command: node ./src/createTag/index.js
  create-release:
    working_directory: ~/repo
    docker:
      - image: node:8.8.0
    steps:
      - run:
          name: Create Release
          command: node ./src/createRelease/index.js
    
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
          filters:
          tags:
            only: /.*/
      - create-tag
          filters:
            branches:
              only: master
      - create-release
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
