version: 2

jobs:
  build:
    docker:
      - image: node:8.8.0
    environment:
      - NPM_CONFIG_LOGLEVEL: warn
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
  create_tag:
    docker:
      - image: node:8.8.0
    working_directory: ~/repo
    steps:
      run: node ./src/createTag/index.js;
  create_release:
    docker:
      - image: node:8.8.0
    working_directory: ~/repo
    steps:
      run: node ./src/createRelease/index.js;

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - create_tag:
          requires:
            - build
          filters:
            branch:
              only: master
      - create_release:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
